### ISSUE TITLE
Relative path between texture path and export directory on diff drives causes Exception

### ISSUE THREAD

**Issue by Supercraft0815** [X-Plane/XPlane2Blender#332]
Hi,

Every time I get a Error during the Export:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\scripts\addons\io_xplane2blender\xplane_export.py", line 118, in execute
    if self._writeXPlaneFile(xplaneFile, export_directory) == False:
  File "C:\Program Files\Blender Foundation\Blender\scripts\addons\io_xplane2blender\xplane_export.py", line 200, in _writeXPlaneFile
    out = xplaneFile.write()
  File "C:\Program Files\Blender Foundation\Blender\scripts\addons\io_xplane2blender\xplane_types\xplane_file.py", line 467, in write
    o += self.header.write()
  File "C:\Program Files\Blender Foundation\Blender\scripts\addons\io_xplane2blender\xplane_types\xplane_header.py", line 517, in write
    self.init()
  File "C:\Program Files\Blender Foundation\Blender\scripts\addons\io_xplane2blender\xplane_types\xplane_header.py", line 143, in init
    self.non_draped_attributes['TEXTURE'].setValue(self.getTexturePath(self.xplaneFile.options.texture, exportdir, blenddir))
  File "C:\Program Files\Blender Foundation\Blender\scripts\addons\io_xplane2blender\xplane_types\xplane_header.py", line 484, in getTexturePath
    texpath = os.path.relpath(texpath, exportdir)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\ntpath.py", line 574, in relpath
    path_drive, start_drive))
ValueError: path is on mount 'D:', start on mount 'C:'

location: <unknown location>:-1

Can every person help me?

Thank you very much and great evening
Alex :D

**Comment by tngreene** [comment]
Where is your .blend file stored and where are your textures stored?

**Comment by Supercraft0815** [comment]
my .blend is on the Desktop and the texture is on my 2. hard disk

**Comment by Supercraft0815** [comment]
Ahhh, I now what you mean. I put the .blend on the same disk as the texture and now it works.

Thank you so much
Great evening
Alex :D

**Comment by tngreene** [comment]
I'm actually turning this into a bug to fix instead of closing it, despite your problem being solved. This should preferably work, or at least crash gracefully with a good error.
