### ISSUE TITLE
"Upgrade to 2.8x required" in Add-ons

### ISSUE THREAD

**Issue by rlipoff** [X-Plane/XPlane2Blender#545]
I'm using Blender 2.82, but after installing XPlane2Blender v3.5.0-rc.1, the add-on shows "Upgrade to 2.8x required" and a warning icon.

**Comment by mirkojovic** [comment]
Trying to replicate the same situation, the console let me know that some module can't be imported. This is de otput from:
' ' ' 
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 330, in enable
    importlib.reload(mod)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 630, in _exec
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\mirko\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\io_xplane2blender\__init__.py", line 39, in <module>
    imp.reload(xplane_ui)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 630, in _exec
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\mirko\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\io_xplane2blender\xplane_ui.py", line 15, in <module>
    from .xplane_helpers import getColorAndLitTextureSlots
ImportError: cannot import name 'getColorAndLitTextureSlots' from 'io_xplane2blender.xplane_helpers' (C:\Users\mirko\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\io_xplane2blender\xplane_helpers.py)


' ' '

**Comment by arb65912** [comment]
Latest version of the exporter is 4.0.0-beta.1
But you still will not be able to import any XP objects

**Comment by mirkojovic** [comment]
In `__init__.py` changing line number `28`, solved it partially

   ` "blender": (2, 7, 8) `  -->  `"blender": (2, 80, 0)`
```
bl_info = {
    "name": "Export: X-Plane (.obj)",
    "author": "Author Tester",
    "version": (3, 5, 0),
    "blender": (2, 80, 0),
    "location": "File > Import/Export > X-Plane",
    "description": "Import and Export X-Plane objects/planes (.obj format)",
    "warning": "",
    "wiki_url": "https://github.com/der-On/XPlane2Blender/wiki",
    "tracker_url": "https://github.com/der-On/XPlane2Blender/issues",
    "category": "Import-Export"
```

But afetr this change, another error occurs.

```
	Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\modules\addon_utils.py", line 384, in enable
    mod.register()
  File "C:\Users\mirko\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_xplane2blender\__init__.py", line 69, in register
    xplane_props.addXPlaneRNA()
AttributeError: module 'io_xplane2blender.xplane_props' has no attribute 'addXPlaneRNA'
```

I searched into this file, and the reference exists, not as a attribute, but as a function.

**Comment by tngreene** [comment]
Blender 2.80 and up is significantly different from Blender 2.79, simply changing the version number won't fix it. If you want to use Blender 2.80 use the latest 4.0.0-beta.1
