### ISSUE TITLE
export XP12 lights fails (xplane2blender 4.2.0, blender v2.83)

### ISSUE THREAD

**Issue by fsspn** [X-Plane/XPlane2Blender#712]
Wanted to create an object, that shows all X-Plane 12 lights to have a visual example. (405 lights, aircraft lights excluded).
Export shows this error report:

Traceback (most recent call last):
  File "C:\Users\alfa\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_xplane2blender\xplane_ops.py", line 586, in execute
    bpy.ops.export.xplane_obj(filepath=self.initial_dir, export_is_relative=True)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\alfa\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_xplane2blender\xplane_export.py", line 104, in execute
    self.only_selected_roots            
  File "C:\Users\alfa\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_xplane2blender\xplane_types\xplane_file.py", line 75, in createFilesFromBlenderRootObjects
    xplane_file = createFileFromBlenderRootObject(potential_root, view_layer)
  File "C:\Users\alfa\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_xplane2blender\xplane_types\xplane_file.py", line 132, in createFileFromBlenderRootObject
    xplane_file.create_xplane_bone_hiearchy(exportable_root)
  File "C:\Users\alfa\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_xplane2blender\xplane_types\xplane_file.py", line 614, in create_xplane_bone_hiearchy
    for o in all_allowed_objects
  File "C:\Users\alfa\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_xplane2blender\xplane_types\xplane_file.py", line 596, in recurse
    recurse(child_obj, parent_bone, allowed_children(child_obj))
  File "C:\Users\alfa\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_xplane2blender\xplane_types\xplane_file.py", line 596, in recurse
    recurse(child_obj, parent_bone, allowed_children(child_obj))
  File "C:\Users\alfa\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_xplane2blender\xplane_types\xplane_file.py", line 516, in recurse
    new_xplane_obj.collect()
  File "C:\Users\alfa\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_xplane2blender\xplane_types\xplane_light.py", line 395, in collect
    p_arg, self.params[p_arg]
KeyError: '10000cd'

location: C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\bpy\ops.py:201

location: <unknown location>:-1

**Comment by fsspn** [comment]
seams to be erroneous automatic lights in X-Plane12, not only one.
