### ISSUE TITLE
Issue while exporting with xplane2blender 4.2.0 version

### ISSUE THREAD

**Issue by ArnavSharmaz0602** [X-Plane/XPlane2Blender#737]
Hey there, I am getting the following issue while trying to export objects from blender. I have never ever seen this issue arise before, this is happening the very first time for some reason : 
Python: Traceback (most recent call last):
  File "C:\Users\sh_ar\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_xplane2blender\xplane_ops.py", line 586, in execute
    bpy.ops.export.xplane_obj(filepath=self.initial_dir, export_is_relative=True)
  File "C:\Blender\4.2.0\blender-4.2.0-beta+v42.bf2e59e1dd58-windows.amd64-release\blender-4.2.0-beta+v42.bf2e59e1dd58-windows.amd64-release\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\sh_ar\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_xplane2blender\xplane_export.py", line 107, in execute
    if not self._writeXPlaneFile(xplaneFile, export_directory):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sh_ar\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_xplane2blender\xplane_export.py", line 217, in _writeXPlaneFile
    out = xplaneFile.write()
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\sh_ar\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_xplane2blender\xplane_types\xplane_file.py", line 749, in write
    self.mesh.collectXPlaneObjects(self.get_xplane_objects())
  File "C:\Users\sh_ar\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_xplane2blender\xplane_types\xplane_mesh.py", line 82, in collectXPlaneObjects
    mesh.calc_normals_split()
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Mesh' object has no attribute 'calc_normals_split'
Location: C:\Blender\4.2.0\blender-4.2.0-beta+v42.bf2e59e1dd58-windows.amd64-release\blender-4.2.0-beta+v42.bf2e59e1dd58-windows.amd64-release\4.2\scripts\modules\bpy\ops.py:109

**Comment by ArnavSharmaz0602** [comment]
![Screenshot (185)](https://github.com/X-Plane/XPlane2Blender/assets/103421322/7f044a11-4377-4fb6-89c7-4d1ba21ec239)
By the way, I've also added the screenshot I had taken from blender while working....
